<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Tyuiu.ShalaevaVV.Sprint0.Task4.V0</AssemblyName>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Tyuiu.ShalaevaVV.Sprint0.Task4.V0_</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tyuiu.ShalaevaVV.Sprint0.Task4.V0.Lib\Tyuiu.ShalaevaVV.Sprint0.Task4.V0.Lib.csproj" />
  </ItemGroup>

</Project>
